Implement transitive closure for Cassandra
hawkular/hawkular-inventory pull request #320
Opened 2016-11-30 16:01 UTC by jotak

2016-11-30 16:03 UTC, jotak commented on hawkular-inventory-impl-cassandra/src/main/java/org/hawkular/inventory/impl/cassandra/CassandraBackend.java
> +                    Statement q = select().all().from(table).where(in(Statements.NAME, Arrays.asList(relationshipNames)));
For this algorithm I have to query on "name", which means we should create an index for that

2016-11-30 19:35 UTC, metlos requested changes

2016-11-30 19:35 UTC, metlos commented on hawkular-inventory-impl-cassandra/src/main/java/org/hawkular/inventory/impl/cassandra/CassandraBackend.java
> +                    Statement q = select().all().from(table).where(in(Statements.NAME, Arrays.asList(relationshipNames)));
I glossed over this when we were discussing your gist, but I don't know if this is really desirable.. Here you request all relationships with given name. Given we almost exclusively use this method to compute over `contains` relationships, this list is going to be absolutely huge (N less than the total number of entities in the whole inventory in all tenants, where N is the number of tenants). I understand the motivation of doing this with only a single query, but I am not sure if this is going to be feasible.

Maybe we could think about the "store whole subtree" idea circulated on the call to be used for this, too...

2016-11-30 19:35 UTC, metlos commented on hawkular-inventory-impl-cassandra/src/main/java/org/hawkular/inventory/impl/cassandra/CassandraBackend.java
> +    private Observable<String> getRelationshipTables(Relationships.Direction direction) {
Is it necessary to wrap the table name in an observable here when you always do `Observable.just()`?

2016-11-30 19:35 UTC, metlos commented on hawkular-inventory-impl-cassandra/src/main/java/org/hawkular/inventory/impl/cassandra/CassandraBackend.java
> +        Multimap<String, Row> mapBySource = Multimaps.index(relationships, row -> row.getString(Statements.SOURCE_CP));
Does the `SOURCE_CP` work in both directions?

2016-11-30 19:35 UTC, metlos commented on hawkular-inventory-impl-cassandra/src/main/java/org/hawkular/inventory/impl/cassandra/CassandraBackend.java
>      public Set<Row> getRelationships(Row entity, Relationships.Direction direction, String... names) {
I know that the model changes a lot, but could you update this reflect the latest model, where relationships are modelled in 3 tables? One "main" table, and in/out tables that are meant used for hops and filtering.

2016-11-30 19:35 UTC, metlos commented on hawkular-inventory-impl-cassandra/src/main/java/org/hawkular/inventory/impl/cassandra/Statements.java
> +    static final Map<String, String> RELATIONSHIP_MAIN_CP = ImmutableMap.<String, String>builder()
This I think becomes unnecessary in the latest version of the model where we have 3 relationship tables.

2016-11-30 19:35 UTC, metlos commented on hawkular-inventory-impl-cassandra/src/test/java/org/hawkular/inventory/impl/cassandra/CassandraBackendTest.java
> +        List<Row> relationships = Lists.newArrayList(
What's the performance characteristics of this with say 20000 relationships processed where only let's say 20 are in the resulting closure?

2016-12-01 08:20 UTC, jotak commented on hawkular-inventory-impl-cassandra/src/main/java/org/hawkular/inventory/impl/cassandra/CassandraBackend.java
> +    private Observable<String> getRelationshipTables(Relationships.Direction direction) {
We need to create an observable pipeline soon or later, and it's a pretty way (well, "pretty" is subjective) to handle single table case (incoming and outgoing) and multiple tables case (both) in the same, general way. So there's no specific code for "both".

2016-12-01 08:21 UTC, jotak commented on hawkular-inventory-impl-cassandra/src/main/java/org/hawkular/inventory/impl/cassandra/CassandraBackend.java
> +        Multimap<String, Row> mapBySource = Multimaps.index(relationships, row -> row.getString(Statements.SOURCE_CP));
I guess not - btw I need to understand your new data model

2016-12-01 08:26 UTC, jotak commented on hawkular-inventory-impl-cassandra/src/main/java/org/hawkular/inventory/impl/cassandra/CassandraBackend.java
> +                    Statement q = select().all().from(table).where(in(Statements.NAME, Arrays.asList(relationshipNames)));
Given what we said yesterday, would it make sense to add a feedId in the primary keys?

2016-12-01 10:11 UTC, metlos commented on hawkular-inventory-impl-cassandra/src/main/java/org/hawkular/inventory/impl/cassandra/CassandraBackend.java
> +    private Observable<String> getRelationshipTables(Relationships.Direction direction) {
Agreed, let's keep it that way then...

2016-12-01 10:13 UTC, metlos commented on hawkular-inventory-impl-cassandra/src/main/java/org/hawkular/inventory/impl/cassandra/CassandraBackend.java
> +                    Statement q = select().all().from(table).where(in(Statements.NAME, Arrays.asList(relationshipNames)));
We also compute the transitive closure when deleting stuff - when you delete an entity, you also delete everything it contains, so adding just the `feedId` wouldn't help in that case.

2016-12-01 17:38 UTC, jotak commented
@metlos I changed the closure algo so that it's not reading everything at once. Now it performs queries step by step, which is not necessarily what we want in the end but at least it should work.

I decoupled the closure algo so that we can change that easily later: all we'll have to do is to provide a function that gives relationships from a vertex (no matters if it reads from memory or from DB)

2016-12-02 17:47 UTC, jotak commented on hawkular-inventory-impl-cassandra/src/test/java/org/hawkular/inventory/impl/cassandra/CassandraInventoryDBTest.java
> +        Row apple = BACKEND.persist(
Note for self: clean up on tearDown

2016-12-05 16:20 UTC, jotak commented
@metlos , I rebased on your latest changes and had to squash the commits for that.

Some notes here:

- In relationship_in/out, I had to remove some part of the primary key that you added. I don't know if it was something necessary for what's you're doing, but in my case this PK was breaking my queries. Another option would be to add secondary indexes. I hope we can avoid creating yet another set of tables.

- In Statements class I created methods that directly return the Observable<Row>, I think it's better that at least this class manages statements bindings so that we can see both queries and bindings in the same class.

2016-12-06 14:19 UTC, merged